import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";

export default function Home() {
  const router = useRouter();
  const [name, setName] = useState("ganesh");
  const handClick = () => {
    router.push({ pathname: "/multiCurency" }, { query: name });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <div className={styles.button}>
            <button className={styles.buttonBody}>{`🌐EN ˅`} </button>
          </div>
          <div className={styles.main}>
            <Image
              src="logo.svg"
              height={200}
              width={200}
              alt="no Img"
              onClick={handClick}
              //() => router.push("/multiCurency")
            />
          </div>
          <div className={styles.content}>
            <h3 className={styles.text}>Airopay</h3>
            <p className={styles.text}>Welcome to your Bankless world</p>
          </div>
        </div>
      </main>
    </>
  );
}
